### ISSUE TITLE
classnames & classnames-loader

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/starter-kit#33]
We're currently using both pure `classnames` and `classnames-loader` in some of our projects. James and I discovered this just now and thought it was a mistake - `className={s(s.myClass` looks very much like a find-and-replace accident.

Can we agree on one approach and make it standard? In my opinion `classnames-loader` isn't obvious,  and while it's a very simple package, it doesn't seem to be very heavily used or maintained.  I'd definitely recommend sticking with classNames even though it requires an extra import line, because it's much more obvious and doesn't implicitly depend on webpack.

**Comment by birkir** [comment]
Allright, makes sense. I actually prefer the classname loader style probably just because I don't use it like your find-replace accident.

```js
({ active }) => <div className={s('item', { active }) />;
// vs
({ active }) => <div className={classNames(s.item, { [s.active]: active })} />;
```

The main difference is that the classnames-loader makes you don't have to deal with the generated classnames, but the style-loader does, hence all the `[s.foo]: true` in an object.

**Comment by elliottkember** [comment]
Oh dang, that's cool. I'll try it for a project. I do wonder if we could make it more obvious, but I can't think of anything. Maybe I'll just write it down in the readme or somewhere.
